# Document:
# http://simiki.org/docs/configuration.html

url: http://miniminyi.com/wiki
title: my wiki
keywords: wiki
description: 
author: MiniMinyi
deploy: git
remote: https://github.com/MiniMinyi/miniminyi.github.io
root: /wiki
theme: yasimple
